[Unit]
AssertPathIsMountPoint = /var/www/data@%i/
AssertPathIsMountPoint = /var/www/html@%i/
RequiresMountsFor = /var/www/data@%i/
RequiresMountsFor = /var/www/html@%i/

[Service]
BindPaths = /var/www/html@%i/
BindReadOnlyPaths = /var/www/html@%i/
Environment = "HTTPD_DOCUMENT_ROOT=/var/www/html@%i/"
